name: Android CI/CD

on:
  push:
    branches:
      - "development"
  pull_request:
    branches:
      - "development"

jobs:
  # CI
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Decrypt and Unzip File
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.LEX_SECRET }}" --output creds.zip creds.zip.gpg
          jar xvf creds.zip
      - name: Check files in directory
        run: |
          ls -ltr .
      - name: Check files in directory
        run: |
          cd creds && ls -ltr .
      - name: Move file to assests/NLU directory 
        run: |
          mv ./creds/Lex_Credentials.xml ./assets/NLU
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 12.x
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Install Flutter dependencies
        run: flutter pub get
        # Add build runner commands here if you have any
      - name: Run the tests
        run: flutter test
      - name: Build App Bundle
        run: flutter build appbundle
      - name: Upload artifact to Github
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: ./build/app/outputs/apk/release/app-release.apk
  # CD
  deploy_android:
    runs-on: ubuntu-latest
    needs: [build_android]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Decrypt and Unzip File
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.LEX_SECRET }}" --output creds.zip creds.zip.gpg
          jar xvf creds.zip
      - name: Check files in directory
        run: |
          ls -ltr .
      - name: Check files in directory
        run: |
          cd creds && ls -ltr .
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.LEX_SECRET }}" --output creds.zip creds.zip.gpg
          jar xvf creds.zip
      - name: Check files in directory
        run: |
          ls -ltr .
      - name: Check files in directory
        run: |
          cd creds && ls -ltr .
      - name: Move file to assests/NLU directory
        run: |
          mv ./creds/Lex_Credentials.xml ./assets/NLU
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 12.x
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Build the APK
        run: flutter build apk --release --split-per-abi
